package storage

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// Preset represents a saved configuration generated by the modeling pipeline
type Preset struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Payload   string `json:"payload"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// PresetStore provides an interface to manage preset persistence
type PresetStore struct {
	client *GCSClient
	bucket string
	prefix string
}

// NewPresetStore creates a new GCS-backed preset store
func NewPresetStore(client *GCSClient, bucket string) *PresetStore {
	return &PresetStore{
		client: client,
		bucket: bucket,
		prefix: "presets/",
	}
}

// Save creates or overwrites a preset
func (s *PresetStore) Save(ctx context.Context, p *Preset) error {
	if p.ID == "" {
		p.ID = uuid.New().String()
	}
	if p.CreatedAt == "" {
		p.CreatedAt = time.Now().UTC().Format(time.RFC3339)
	}
	p.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	data, err := json.Marshal(p)
	if err != nil {
		return err
	}

	objectName := fmt.Sprintf("%s%s.json", s.prefix, p.ID)
	return s.client.WriteFile(ctx, s.bucket, objectName, data)
}

// Get retrieves a specific preset by ID
func (s *PresetStore) Get(ctx context.Context, id string) (*Preset, error) {
	objectName := fmt.Sprintf("%s%s.json", s.prefix, id)
	data, err := s.client.ReadFile(ctx, s.bucket, objectName)
	if err != nil {
		return nil, err
	}

	var p Preset
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return &p, nil
}

// List retrieves all presets currently saved
func (s *PresetStore) List(ctx context.Context) ([]*Preset, error) {
	files, err := s.client.ListFiles(ctx, s.bucket, s.prefix)
	if err != nil {
		return nil, err
	}

	var presets []*Preset
	for _, f := range files {
		if strings.HasSuffix(f, ".json") {
			data, err := s.client.ReadFile(ctx, s.bucket, f)
			if err != nil {
				continue
			}
			var p Preset
			if err := json.Unmarshal(data, &p); err == nil {
				presets = append(presets, &p)
			}
		}
	}
	return presets, nil
}

// Delete removes a preset from storage
func (s *PresetStore) Delete(ctx context.Context, id string) error {
	objectName := fmt.Sprintf("%s%s.json", s.prefix, id)
	return s.client.DeleteFile(ctx, s.bucket, objectName)
}
