package storage

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// ChatMessage represents a single turn in the post-generation refinement flow
type ChatMessage struct {
	Role    string `json:"role"` // "user" or "model"
	Content string `json:"content"`
}

// BlockParameter represents a single knob or slider value
type BlockParameter struct {
	Name  string `json:"name"`
	Type  string `json:"type"` // "slider", "toggle", "dropdown"
	Value string `json:"value"`
	Unit  string `json:"unit,omitempty"`
}

// EffectBlock represents a single gear block in the signal chain
type EffectBlock struct {
	ID         string           `json:"id"`
	Type       string           `json:"type"` // e.g. "Amplifier", "Overdrive"
	Model      string           `json:"model"`
	Parameters []BlockParameter `json:"parameters"`
}

// StructuredPreset wraps the signal chain per guitar variation
type StructuredPreset struct {
	Guitars map[string][]EffectBlock `json:"guitars"`
}

// Preset represents a saved configuration generated by the modeling pipeline
type Preset struct {
	ID               string        `json:"id"`
	Name             string        `json:"name"`
	Payload          string        `json:"payload"` // JSON string of StructuredPreset or legacy HTML map
	BuilderStatement string        `json:"builder_statement,omitempty"`
	ChatHistory      []ChatMessage `json:"chat_history,omitempty"`
	CreatedAt        string        `json:"created_at"`
	UpdatedAt        string        `json:"updated_at"`
}

// Client defines the interface for underlying storage operations
type Client interface {
	ReadFile(ctx context.Context, bucket, object string) ([]byte, error)
	WriteFile(ctx context.Context, bucket, object string, data []byte) error
	ListFiles(ctx context.Context, bucket, prefix string) ([]string, error)
	DeleteFile(ctx context.Context, bucket, object string) error
	Close()
}

// PresetStore provides an interface to manage preset persistence
type PresetStore struct {
	client Client
	bucket string
	prefix string
}

// NewPresetStore creates a new generic preset store
func NewPresetStore(client Client, bucket string) *PresetStore {
	return &PresetStore{
		client: client,
		bucket: bucket,
		prefix: "presets/",
	}
}

// Save creates or overwrites a preset
func (s *PresetStore) Save(ctx context.Context, p *Preset) error {
	if p.ID == "" {
		p.ID = uuid.New().String()
	}
	if p.CreatedAt == "" {
		p.CreatedAt = time.Now().UTC().Format(time.RFC3339)
	}
	p.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	data, err := json.Marshal(p)
	if err != nil {
		return err
	}

	objectName := fmt.Sprintf("%s%s.json", s.prefix, p.ID)
	return s.client.WriteFile(ctx, s.bucket, objectName, data)
}

// Get retrieves a specific preset by ID
func (s *PresetStore) Get(ctx context.Context, id string) (*Preset, error) {
	objectName := fmt.Sprintf("%s%s.json", s.prefix, id)
	data, err := s.client.ReadFile(ctx, s.bucket, objectName)
	if err != nil {
		return nil, err
	}

	var p Preset
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return &p, nil
}

// List retrieves all presets currently saved
func (s *PresetStore) List(ctx context.Context) ([]*Preset, error) {
	files, err := s.client.ListFiles(ctx, s.bucket, s.prefix)
	if err != nil {
		return nil, err
	}

	var presets []*Preset
	for _, f := range files {
		if strings.HasSuffix(f, ".json") {
			data, err := s.client.ReadFile(ctx, s.bucket, f)
			if err != nil {
				continue
			}
			var p Preset
			if err := json.Unmarshal(data, &p); err == nil {
				presets = append(presets, &p)
			}
		}
	}
	return presets, nil
}

// Delete removes a preset from storage
func (s *PresetStore) Delete(ctx context.Context, id string) error {
	objectName := fmt.Sprintf("%s%s.json", s.prefix, id)
	return s.client.DeleteFile(ctx, s.bucket, objectName)
}
