steps:
  - name: 'golang:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go run cmd/eval/main.go
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp *_multi.html *_mono.md gs://weitzer-sound-builder/eval-logs/
